version: "3.8"

services:
  app:
    tty: true
    container_name: mytodoapp
    image: mytodoapp
    build:
      context: .
      target: production
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
